In [21]:
import numpy as np
import pandas as pd
from google.colab import drive
import os
import torch
import torch.nn as nn
import torch.optim as optim
import torch
from torch.utils.data import Dataset, DataLoader
import pickle
import random
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import balanced_accuracy_score,accuracy_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,f1_score,confusion_matrix,roc_auc_score,ConfusionMatrixDisplay,precision_score,recall_score
import numpy as np
from scipy import signal
import xgboost as xgb
import warnings
warnings.filterwarnings('ignore')

In [2]:
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
main_dir = 'drive/MyDrive/23Spring-MLMA/isolated/'

patient = ["001","002","003","004","005","006"]
test_split = [["01","02"],["03","04"],["05","06"],["07","08"],["09","10"]]
val_split = ['03','01',"04","05","06"]

os.listdir(main_dir)

['002',
 '005',
 '004',
 '003',
 '001',
 '006',
 'User_dependent',
 'Isolated Model',
 'User_independent',
 'XGboost0.pkl',
 'XGboost1.pkl',
 'XGboost2.pkl',
 'XGboost3.pkl',
 'XGboost4.pkl',
 'XGboost5.pkl']

In [45]:
# -*- coding: utf-8 -*-
"""preprocess.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1_HGxPyUOCJ3wnMfPbXl7sqWSz-jsCMGe
"""
# input: data (type: numpy array)(shape: (time, 2))
# output: data (type: numpy array)(shape: (100, 2))
import numpy as np
from scipy import signal

def preprocess(data):
  # Delete silent part
  data = data.astype(float)
  n_size = 50
  n_len = int(data.shape[0]/n_size)
  std_data = np.zeros((n_size, 2))
  for i in range(n_size):
    seg_data_x = data[i*n_len:i*n_len+n_len, 0]
    seg_data_y = data[i*n_len:i*n_len+n_len, 1]
    std_data[i, 0] = np.std(seg_data_x)
    std_data[i, 1] = np.std(seg_data_y)
  pass_threshold = 1
  pass_idx_x = np.where(std_data[:,0] >= pass_threshold)[0]
  pass_idx_y = np.where(std_data[:,1] >= pass_threshold)[0]
  if len(pass_idx_x) == 0:
    start_idx = max(0, pass_idx_y[0] - 1)
    end_idx = min(data.shape[0],pass_idx_y[-1] + 1)
  elif len(pass_idx_y) == 0:
    start_idx = max(0, pass_idx_x[0] - 1)
    end_idx = min(data.shape[0],pass_idx_x[-1] + 1)
  else:
    start_idx = max(0,min(pass_idx_x[0], pass_idx_y[0]) - 1)
    end_idx = min(data.shape[0],max(pass_idx_x[-1], pass_idx_y[-1]) + 1)
  
  # resample to 100 data points
  data = signal.resample(data[start_idx*n_len:end_idx*n_len, :], 100, axis=0)
  # scale
  data = (data - data.min(axis=0, keepdims=True))/(data.max(axis=0, keepdims=True) - data.min(axis=0, keepdims=True))
  return data

# get file list for 1 patient
def get_file_list(path):
    file_list = []
    label = []
    for i in os.listdir(path):
        file_list.append(i)
        l = int(i.split("_")[-1].split(".")[0])-1
        label.append(l)
    return label,file_list

# get feature from 1 file and preprocess
def get_feature(path):
    f = []
    a = pd.read_csv(path,names=["vertical","horizontal"])
    a = np.array(a)
    a = preprocess(a)
    for j in a[:,0]:
        f.append(j)        
    for j in a[:,1]:
        f.append(j)
    return f

def evaluate(y_true, y_pred,y_prob):
    f1_micro = f1_score(y_true, y_pred,average = 'micro')
    f1_macro = f1_score(y_true, y_pred,average = 'macro')
    precision_micro = precision_score(y_true, y_pred, average='micro')
    precision_macro = precision_score(y_true, y_pred, average='macro')
    recall_micro = recall_score(y_true, y_pred, average='micro')
    recall_macro = recall_score(y_true, y_pred, average='macro')
    acc = accuracy_score(y_true, y_pred)
    auc = roc_auc_score(y_true,y_prob,multi_class="ovr",average="micro")

    return f1_micro,f1_macro,precision_micro,precision_macro,recall_micro,recall_macro,acc,auc

# Split on patient level - User-independent


> 6-fold cross-validation





In [13]:
# self identified test_split
def my_train_test_split_user_independent(test_patient,val_patient,train_patient):
    X_test = []
    X_train = []
    X_val = []
    y_val = []
    y_train = []
    y_test = []
    for p in train_patient:
        path = str(main_dir+p+"/isolated_strokes/")#str("../../../../data/isolated 2/"+p+"/isolated_strokes/")
        label,file_list = get_file_list(path)
        for i in range(len(file_list)):
            file = file_list[i]
            file_label = label[i]
            feature = get_feature(str(path+file))
            X_train.append(feature)
            y_train.append(file_label)
        
    path = str(main_dir+test_patient+"/isolated_strokes/")#str("../../../../data/isolated 2/"+test_patient+"/isolated_strokes/")
    label,file_list = get_file_list(path)
    for i in range(len(file_list)):
        file = file_list[i]
        file_label = label[i]
        feature = get_feature(str(path+file))
        X_test.append(feature)
        y_test.append(file_label)
    
    path = str(main_dir+val_patient+"/isolated_strokes/")# str("../../../../data/isolated 2/"+val_patient+"/isolated_strokes/")
    label,file_list = get_file_list(path)
    for i in range(len(file_list)):
        file = file_list[i]
        file_label = label[i]
        feature = get_feature(str(path+file))
        X_val.append(feature)
        y_val.append(file_label)

    X_train = np.array(X_train)
    X_test = np.array(X_test)
    y_train = np.array(y_train)
    y_test = np.array(y_test)
    X_val = np.array(X_val)
    y_val = np.array(y_val)
    return X_train,X_test, X_val,y_val,y_train,y_test

In [46]:
import xgboost as xgb
def train(train_feature,train_label,test_feature,test_label,n,d):
    # 定义模型
    model = xgb.XGBClassifier(n_estimators=n, max_depth=d, objective='multi:softprob', num_class=12, random_state=42)

    # 训练模型
    model.fit(train_feature, train_label)#,eval_set=[(test_feature, test_label)])

    # 预测测试集
    y_pred_p = model.predict_proba(test_feature)
    y_pred = model.predict(test_feature)

    # 计算metrics
    f1_micro,f1_macro,precision_micro,precision_macro,recall_micro,recall_macro,acc,auc = evaluate(test_label, y_pred,y_pred_p)

    return f1_micro,f1_macro,precision_micro,precision_macro,recall_micro,recall_macro,acc,auc,model

In [48]:
test_patien_list = ["001","002","003","004","005","006"]
val_patient_list = ["002","003","004","005","006","001"]
output_pck = []
F1 = 0
D = [2,4,6,8,10]
N = [10,100,500,1000]
output = dict()

for t in range(len(test_patien_list)):
    train_patient= ["001","002","003","004","005","006"]
    test_patient = test_patien_list[t]
    val_patient = val_patient_list[t]
    train_patient.remove(test_patient)
    train_patient.remove(val_patient)
    print(test_patient,val_patient,train_patient)
    X_train,X_test, X_val,y_val,y_train,y_test = my_train_test_split_user_independent(test_patient,val_patient,train_patient)

    # output = dict()
    # output["test_split"] = t
    # grid_search_output = grid_search(X_train,X_test, X_val,y_val,y_train,y_test)
    # output["grid_search"] = grid_search_output
    # output_pck.append(output)
    for n in N:
      for d in D:
        output = dict()
        f1_micro,f1_macro,precision_micro,precision_macro,recall_micro,recall_macro,acc,auc,model = train(X_train,y_train,X_val,y_val,n,d)
        output['n']=n;output['d']=d;output["test_split"] =t;output['model']=model
        output['f1_micro']=f1_micro;output['f1_macro']=f1_macro;output['precision_micro']=precision_micro;output['precision_macro']=precision_macro
        output['recall_micro']=recall_micro;output['recall_macro']=recall_macro;output['acc']=acc;output['auc']=auc
        # print(output)
        output_pck.append(output)
    

# 保存模型
pickle.dump(output_pck, open(main_dir+"XGboost_User_Independent"+".pkl", 'wb'))

001 002 ['003', '004', '005', '006']
002 003 ['001', '004', '005', '006']
003 004 ['001', '002', '005', '006']
004 005 ['001', '002', '003', '006']
005 006 ['001', '002', '003', '004']
006 001 ['002', '003', '004', '005']


In [52]:
f1=np.zeros((len(N),len(D)))
accu=np.zeros((len(N),len(D)))
for n in range(len(N)):
  for d in range(len(D)):
    for i in range(len(output_pck)):
      if output_pck[i]['n']==N[n] and output_pck[i]['d']==D[d]:
        f1[n][d]+=output_pck[i]['f1_macro']
        accu[n][d]+=output_pck[i]['acc']
f1/=len(test_patien_list)
accu/=len(test_patien_list)

In [53]:
print(f1)
f1.argmax()

[[0.58495284 0.59736904 0.59192345 0.59226089 0.59513006]
 [0.6087729  0.62204923 0.61175277 0.59818223 0.59645906]
 [0.60279175 0.60886647 0.60888162 0.6043282  0.59688172]
 [0.59974503 0.6106403  0.60888162 0.6043282  0.59688172]]


6

In [54]:
print(accu)
accu.argmax()

[[0.60524583 0.61077824 0.60664582 0.61080119 0.6107438 ]
 [0.63280627 0.63975052 0.63282922 0.62040901 0.62043178]
 [0.62727348 0.63146292 0.63006292 0.62868533 0.62318679]
 [0.6244957  0.6328518  0.63006292 0.62868533 0.62318679]]


6

max_depth=4, 
n_estimators=100

In [55]:
f1t=0;acct=0;pret=0;rect=0;auct=0;c=0
f1tm=0;pretm=0;rectm=0

for t in range(len(test_patien_list)):
    train_patient= ["001","002","003","004","005","006"]
    test_patient = test_patien_list[t]
    val_patient = val_patient_list[t]
    train_patient.remove(test_patient)
    train_patient.remove(val_patient)
    print(test_patient,val_patient,train_patient)
    X_train,X_test, X_val,y_val,y_train,y_test = my_train_test_split_user_independent(test_patient,val_patient,train_patient)

    for i in range(len(output_pck)):
      if output_pck[i]['test_split']==t and output_pck[i]['n']==100 and output_pck[i]['d']==4:
        # 定义模型
        model = output_pck[i]['model']
        # 预测测试集
        y_pred_p = model.predict_proba(X_test)
        y_pred = model.predict(X_test)
        # 计算metrics
        f1_micro,f1_macro,precision_micro,precision_macro,recall_micro,recall_macro,acc,auc = evaluate(y_test, y_pred,y_pred_p)
        f1t+=f1_macro;pret+=precision_macro;acct+=acc;rect+=recall_macro;auct+=auc;c+=1
        f1tm+=f1_micro;pretm+=precision_micro;rectm+=recall_micro

f1t/=c;acct/=c;pret/=c;rect/=c
f1tm/=c;pretm/=c;rectm/=c;auct/=c

001 002 ['003', '004', '005', '006']
002 003 ['001', '004', '005', '006']
003 004 ['001', '002', '005', '006']
004 005 ['001', '002', '003', '006']
005 006 ['001', '002', '003', '004']
006 001 ['002', '003', '004', '005']


In [58]:
print("test accuracy:",acct)
print("test f1 macro:",f1t)
print("test f1 micro:",f1tm)
print("test precision macro:",pret)
print("test precision micro:",pretm)
print("test recall macro:",rect)
print("test recall micro:",rectm)
print("test auc:",auct)

test accuracy: 0.6481514097758508
test f1 macro: 0.6241804531071385
test f1 micro: 0.6481514097758508
test precision macro: 0.6881567337127192
test precision micro: 0.6481514097758508
test recall macro: 0.648807519640853
test recall micro: 0.6481514097758508
test auc: 0.930161941077547


# User-dependent


> 5-fold cross-validation





In [59]:
# self identified test_split
def my_train_test_split_user_dependent(path,test_split,val_split,file_list,label):
    X_test = []
    X_train = []
    X_val = []
    y_val = []
    y_train = []
    y_test = []
    for f in range(len(file_list)):
        file = file_list[f]
        file_label = label[f]
        #print(file)
        feature = get_feature(str(path+file))
        #print(file.split('_')[2],file_label)
        if file.split('_')[2] in test_split:
            X_test.append(feature)
            y_test.append(file_label)
            #print(file,len(feature))
        elif file.split('_')[2] == val_split:
            X_val.append(feature)
            y_val.append(file_label)
            # print("val ",file)
        else:
            X_train.append(feature)
            y_train.append(file_label)
            # print("train ",file)

    X_train = np.array(X_train)
    X_test = np.array(X_test)
    X_val = np.array(X_val)
    y_train = np.array(y_train)
    y_val = np.array(y_val)
    y_test = np.array(y_test)
    
    return X_train,X_test,X_val,y_val, y_train,y_test

In [68]:
output_pck_pck=[]
for p in patient:
    print(p)
    output_pck = []
    path = str(main_dir+p+"/isolated_strokes/")#str("../../../../data/isolated 2/"+p+"/isolated_strokes/")
    for t in range(len(test_split)):
        print(test_split[t])
        label,file_list = get_file_list(path)
        X_train,X_test,X_val,y_val, y_train,y_test = my_train_test_split_user_dependent(path,test_split[t],val_split[t],file_list,label)
        print(X_val.shape,y_val.shape)
         # build model
        # set parameter 
        # output = dict()
        # output["test_split"] = t
        # grid_search_output = grid_search(X_train,X_test, X_val,y_val,y_train,y_test)
        # output["grid_search"] = grid_search_output
        # output_pck.append(output)

        for n in N:
          for d in D:
            output = dict()
            f1_micro,f1_macro,precision_micro,precision_macro,recall_micro,recall_macro,acc,auc,model = train(X_train,y_train,X_val,y_val,n,d)
            output['n']=n;output['d']=d;output["test_split"] =t;output["patient"] =p;output['model']=model
            output['f1_micro']=f1_micro;output['f1_macro']=f1_macro;output['precision_micro']=precision_micro;output['precision_macro']=precision_macro
            output['recall_micro']=recall_micro;output['recall_macro']=recall_macro;output['acc']=acc;output['auc']=auc
            # print(output)
            output_pck.append(output)
            output_pck_pck.append(output)


        
    # with open(str(main_dir+"/User_dependent/patient_"+p+"_XGboost.pck"), "wb") as output_file:
    #     pickle.dump(output_pck, output_file)
    pickle.dump(output_pck, open(str(main_dir+"User_dependent/patient_"+p+"_XGboost.pck"), "wb"))
        

001
['01', '02']
(12, 200) (12,)
['03', '04']
(12, 200) (12,)
['05', '06']
(12, 200) (12,)
['07', '08']
(12, 200) (12,)
['09', '10']
(12, 200) (12,)
002
['01', '02']
(12, 200) (12,)
['03', '04']
(12, 200) (12,)
['05', '06']
(12, 200) (12,)
['07', '08']
(12, 200) (12,)
['09', '10']
(12, 200) (12,)
003
['01', '02']
(12, 200) (12,)
['03', '04']
(12, 200) (12,)
['05', '06']
(12, 200) (12,)
['07', '08']
(12, 200) (12,)
['09', '10']
(12, 200) (12,)
004
['01', '02']
(12, 200) (12,)
['03', '04']
(12, 200) (12,)
['05', '06']
(12, 200) (12,)
['07', '08']
(12, 200) (12,)
['09', '10']
(12, 200) (12,)
005
['01', '02']
(12, 200) (12,)
['03', '04']
(12, 200) (12,)
['05', '06']
(12, 200) (12,)
['07', '08']
(12, 200) (12,)
['09', '10']
(12, 200) (12,)
006
['01', '02']
(12, 200) (12,)
['03', '04']
(12, 200) (12,)
['05', '06']
(12, 200) (12,)
['07', '08']
(12, 200) (12,)
['09', '10']
(12, 200) (12,)


In [69]:
position=[]
for p in patient:
  print(p)
  f1=np.zeros((len(N),len(D)))
  accu=np.zeros((len(N),len(D)))
  for n in range(len(N)):
    for d in range(len(D)):
      for i in range(len(output_pck_pck)):
        if output_pck_pck[i]['n']==N[n] and output_pck_pck[i]['d']==D[d] and output_pck_pck[i]['patient']==p:
          f1[n][d]+=output_pck_pck[i]['f1_macro']
          accu[n][d]+=output_pck_pck[i]['acc']
  f1/=len(test_split)
  accu/=len(test_split)
  print(f1)
  print(f1.argmax())
  print(accu)
  print(accu.argmax())
  position.append(accu.argmax())

001
[[0.61388889 0.62222222 0.62222222 0.62222222 0.62222222]
 [0.625      0.63333333 0.63333333 0.63333333 0.63333333]
 [0.625      0.63333333 0.63333333 0.63333333 0.63333333]
 [0.625      0.63333333 0.63333333 0.63333333 0.63333333]]
6
[[0.68333333 0.68333333 0.68333333 0.68333333 0.68333333]
 [0.7        0.7        0.7        0.7        0.7       ]
 [0.7        0.7        0.7        0.7        0.7       ]
 [0.7        0.7        0.7        0.7        0.7       ]]
5
002
[[0.63444444 0.63333333 0.63333333 0.63333333 0.63333333]
 [0.66944444 0.65277778 0.65277778 0.65277778 0.65277778]
 [0.66944444 0.65277778 0.65277778 0.65277778 0.65277778]
 [0.66944444 0.65277778 0.65277778 0.65277778 0.65277778]]
5
[[0.7        0.7        0.7        0.7        0.7       ]
 [0.73333333 0.71666667 0.71666667 0.71666667 0.71666667]
 [0.73333333 0.71666667 0.71666667 0.71666667 0.71666667]
 [0.73333333 0.71666667 0.71666667 0.71666667 0.71666667]]
5
003
[[0.60222222 0.58166667 0.58166667 0.58166667 0.

In [72]:
f1tl=[];acctl=[];pretl=[];rectl=[]
f1tml=[];pretml=[];rectml=[];auctl=[]
for pi in range(len(patient)):
    p=patient[pi]
    # print(p)
    path = str(main_dir+p+"/isolated_strokes/")#str("../../../../data/isolated 2/"+p+"/isolated_strokes/")
    f1t=0;acct=0;pret=0;rect=0;auct=0;c=0
    f1tm=0;pretm=0;rectm=0
    for t in range(len(test_split)):
        # print(test_split[t])
        label,file_list = get_file_list(path)
        X_train,X_test,X_val,y_val, y_train,y_test = my_train_test_split_user_dependent(path,test_split[t],val_split[t],file_list,label)
        # print(X_val.shape,y_val.shape)

        for i in range(len(output_pck_pck)):
          if position[pi]==5:
            if output_pck_pck[i]['test_split']==t and output_pck_pck[i]['patient']==p and output_pck_pck[i]['n']==100 and output_pck_pck[i]['d']==2:
              # 定义模型
              model = output_pck_pck[i]['model']
              # 预测测试集
              y_pred_p = model.predict_proba(X_test)
              y_pred = model.predict(X_test)
              # 计算metrics
              f1_micro,f1_macro,precision_micro,precision_macro,recall_micro,recall_macro,acc,auc = evaluate(y_test, y_pred,y_pred_p)
              f1t+=f1_macro;pret+=precision_macro;acct+=acc;rect+=recall_macro;auct+=auc;c+=1
              f1tm+=f1_micro;pretm+=precision_micro;rectm+=recall_micro
          elif position[pi]==6:
            if output_pck_pck[i]['test_split']==t and output_pck_pck[i]['patient']==p and output_pck_pck[i]['n']==100 and output_pck_pck[i]['d']==4:
              # 定义模型
              model = output_pck_pck[i]['model']
              # 预测测试集
              y_pred_p = model.predict_proba(X_test)
              y_pred = model.predict(X_test)
              # 计算metrics
              f1_micro,f1_macro,precision_micro,precision_macro,recall_micro,recall_macro,acc,auc = evaluate(y_test, y_pred,y_pred_p)
              f1t+=f1_macro;pret+=precision_macro;acct+=acc;rect+=recall_macro;auct+=auc;c+=1
              f1tm+=f1_micro;pretm+=precision_micro;rectm+=recall_micro

    f1t/=c;acct/=c;pret/=c;rect/=c
    f1tm/=c;pretm/=c;rectm/=c;auct/=c
    f1tl.append(f1t);acctl.append(acct);pretl.append(pret);rectl.append(rect)
    f1tml.append(f1tm);pretml.append(pretm);rectml.append(rectm);auctl.append(auct)
    print("patient:",p)
    print("test accuracy:",acct)
    print("test f1 macro:",f1t)
    print("test f1 micro:",f1tm)
    print("test precision macro:",pret)
    print("test precision micro:",pretm)
    print("test recall macro:",rect)
    print("test recall micro:",rectm)
    print("test auc:",auct)
    print()


patient: 001
test accuracy: 0.7416666666666666
test f1 macro: 0.7144444444444444
test f1 micro: 0.7416666666666666
test precision macro: 0.725
test precision micro: 0.7416666666666666
test recall macro: 0.7416666666666666
test recall micro: 0.7416666666666666
test auc: 0.9614583333333332

patient: 002
test accuracy: 0.7666666666666667
test f1 macro: 0.7494444444444446
test f1 micro: 0.7666666666666667
test precision macro: 0.7888888888888889
test precision micro: 0.7666666666666667
test recall macro: 0.7666666666666667
test recall micro: 0.7666666666666667
test auc: 0.9467803030303031

patient: 003
test accuracy: 0.7083333333333334
test f1 macro: 0.6846031746031745
test f1 micro: 0.7083333333333334
test precision macro: 0.7147222222222223
test precision micro: 0.7083333333333334
test recall macro: 0.7083333333333334
test recall micro: 0.7083333333333334
test auc: 0.945486111111111

patient: 004
test accuracy: 0.6666666666666667
test f1 macro: 0.6234126984126984
test f1 micro: 0.6666666

In [73]:
print("average test accuracy:",np.mean(acctl))
print("average test f1 macro:",np.mean(f1tl))
print("average test f1 micro:",np.mean(f1tml))
print("average test precision macro:",np.mean(pretl))
print("average test precision micro:",np.mean(pretml))
print("average test recall macro:",np.mean(rectl))
print("average test recall micro:",np.mean(rectml))
print("average test auc:",np.mean(auctl))

average test accuracy: 0.7356884057971015
average test f1 macro: 0.7058862433862435
average test f1 micro: 0.7356884057971015
average test precision macro: 0.7299074074074073
average test precision micro: 0.7356884057971015
average test recall macro: 0.7347222222222224
average test recall micro: 0.7356884057971015
average test auc: 0.9473842075448881
